import { toast } from 'sonner'

/** Generated by vite-plugin-pwa at the site root. */
const SW_URL = '/sw.js'

/**
 * How often an open tab asks the server whether a new worker was deployed.
 * Browsers only check on navigation by default, and an installed iOS PWA can
 * stay open for days — without this poll a Dokploy deploy would not be picked
 * up until the user force-quit the app.
 */
const CHECK_INTERVAL_MS = 60_000

/**
 * Registers the service worker and owns the update policy.
 *
 * The lifecycle is driven straight off the registration rather than through
 * workbox-window: its "was this update mine or external?" heuristics swallow
 * the waiting event for updates found by our own polling.
 *
 * A new build is applied the moment it can be applied invisibly — app in the
 * background, or the user coming back to it — otherwise the user gets a toast,
 * so a reload never lands in the middle of a form.
 */
export function initPwa() {
  if (import.meta.env.DEV) return
  if (!('serviceWorker' in navigator)) return

  let reloading = false
  let updateReady = false
  let sawNewWorker = false
  const hadController = !!navigator.serviceWorker.controller

  navigator.serviceWorker.addEventListener('controllerchange', () => {
    // On a first visit the worker claiming this page is the initial install,
    // not a new build — reloading for it would be a pointless flash.
    if (!hadController && !sawNewWorker) return
    if (reloading) return
    reloading = true
    window.location.reload()
  })

  const start = () => void register()
  if (document.readyState === 'complete') start()
  else window.addEventListener('load', start, { once: true })

  async function register() {
    let registration: ServiceWorkerRegistration
    try {
      registration = await navigator.serviceWorker.register(SW_URL, {
        scope: '/',
      })
    } catch {
      return
    }

    /** Hands over to the new worker; controllerchange above does the reload. */
    const activate = () => {
      if (!registration.waiting) return
      toast.dismiss('pwa-update')
      registration.waiting.postMessage({ type: 'SKIP_WAITING' })
    }

    const announce = () => {
      if (!registration.waiting || updateReady) return
      updateReady = true
      if (document.visibilityState === 'hidden') {
        activate()
        return
      }
      toast('Nuova versione disponibile', {
        id: 'pwa-update',
        description: 'Ricarica per aggiornare Calorico.',
        duration: Number.POSITIVE_INFINITY,
        action: { label: 'Aggiorna', onClick: activate },
      })
    }

    registration.addEventListener('updatefound', () => {
      const installing = registration.installing
      if (!installing) return
      // With nothing active and nothing controlling us this is the very first
      // install, which has no old build to replace.
      const isNewBuild = hadController || !!registration.active
      installing.addEventListener('statechange', () => {
        if (installing.state !== 'installed' || !isNewBuild) return
        sawNewWorker = true
        announce()
      })
    })

    // A worker can already be waiting from an earlier visit in this tab.
    if (registration.waiting && (hadController || registration.active)) {
      sawNewWorker = true
      announce()
    }

    const check = () => {
      if (reloading) return
      void registration.update().catch(() => {})
    }

    window.setInterval(check, CHECK_INTERVAL_MS)
    window.addEventListener('online', check)
    document.addEventListener('visibilitychange', () => {
      // Both transitions are free moments to swap the build: nothing is on
      // screen when hidden, and a fresh start is expected when returning.
      if (updateReady) {
        activate()
        return
      }
      if (document.visibilityState === 'visible') check()
    })

    check()
  }
}
