/**
 * What the API accepts and returns, as this app sees it.
 *
 * Every type here is inferred from the zod schemas in `@calorico/contracts`,
 * which the API parses its requests with and asserts its responses against in
 * its route tests. This file used to be a hand-written mirror of those payloads,
 * and nothing checked that the mirror was still true: a changed response left
 * the client compiling happily against a lie until a screen rendered
 * `undefined`. Re-exporting keeps `@/lib/types` as the one import path screens
 * and hooks use, while the definitions live where both apps can see them.
 *
 * Adding a field? Add it to the contract, not here.
 */
export type {
  ActivityLevel,
  AnalyzedItem,
  AuthResponse,
  BatchEntryInput,
  BodyMetrics,
  BreakdownResponse,
  CheckoutSession,
  Confidence,
  DailyStat,
  DayStats,
  DayTargets,
  DiaryDay,
  DiaryEntry,
  Family,
  FamiliesResponse,
  FamilyInvite,
  FamilyMember,
  Food,
  FoodImage,
  FoodImageKind,
  FoodPortions,
  FoodSource,
  Goal,
  GroceryItem,
  GroceryResponse,
  GrocerySuggestion,
  GrocerySuggestionsResponse,
  InvitePreview,
  Meal,
  MealAnalysis,
  MealShare,
  MealShareWithMacros,
  MeResponse,
  NewFoodInput,
  NotificationSettings,
  Nutrients100,
  PeriodBucket,
  PeriodsResponse,
  PeriodUnit,
  PersonRef,
  PhotoQuota,
  PremiumStatus,
  Profile,
  RecentFood,
  Reminder,
  ReminderKind,
  ReminderPreset,
  SavedMeal,
  SavedMealItem,
  ScanHistoryItem,
  ScanKind,
  ScansResponse,
  Sex,
  StatsResponse,
  SuggestedTargets,
  TargetEstimate,
  TopFood,
  Totals,
  User,
  VisionStatus,
  WeightLog,
  WeightResponse,
  WeightSpan,
} from '@calorico/contracts'
